# dataset model: rosbag, mynteye
dataset: "mynteye"

# rosbag config
rosbag:
  topic_img_left: "/mynteye/gray_left"
  topic_img_right: "/mynteye/gray_right"
  topic_imu: "/mynteye/imu"
  topic_temp: "/mynteye/temp"
